name: cowin_smart_card
description: A GUI based CoWIN Certificate to Smart Card Converter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  file_picker: ^4.3.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pdf: ^3.6.5
  path_provider: ^2.0.8
  native_pdf_renderer: ^4.0.1
  native_pdf_view: ^5.0.0
  flutter_acrylic: ^1.0.0+1
  bitsdojo_window: ^0.1.1+1
  system_theme: ^1.0.1
  rounded_loading_button: ^2.0.8
  flutter_switch: ^0.3.2
  fluent_ui:
    git: https://github.com/bdlukaa/fluent_ui.git
  printing: ^5.7.2
  flutter_phoenix: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  msix: ^2.8.18



flutter:
  uses-material-design: true

  assets:
    - logo.png


  fonts:
    - family: Risque
      fonts:
        - asset: assets/fonts/Risque-Regular.otf

msix_config:
  display_name: Cowin Smart Print
  publisher_display_name: Shreyam Maity
  identity_name: 25674ShreyamMaity.CoWINSmartPrint
  publisher: CN=338ABBC6-098C-49DA-A6A1-D5D1D1754FD1
  msix_version: 1.0.0.0
  logo_path: assets/logo.png
  output_path: release/
  output_name: installer
  architecture: x64
  language: en-US
  file_extension: .pdf
  store: true
